In [ ]:
import numpy as np

In [3]:
#buat matrix X berukuran 2x3 menggunakan numpy
X = np.array([[12, 4, 7],
              [25, 15, 61]])
print("matriks X:", X)

matriks X: [[12  4  7]
 [25 15 61]]


In [6]:
#tampilkan ukuran dari matrix X
X.shape
print("ukuran dari matrix X adalah:", X.shape)

ukuran dari matrix X adalah: (2, 3)


In [7]:
#tampilkan seluruh elemen dari kolom pertamaa dari matrix X
X[:,0]
print("seluruh elemen dari kolom pertama matrix X adalah;", X[:,0])

seluruh elemen dari kolom pertama matrix X adalah; [12 25]


In [8]:
#tampilkan seluruh elemen pada baris kedua dari matrix X
X[1,:]
print("semua elemen dari baris kedua matrix X adalah:", X[1,:])

semua elemen dari baris kedua matrix X adalah: [25 15 61]


In [10]:
#PYTORCH
import torch

In [13]:
X_pt = torch.tensor([[12, 4, 7],
              [25, 15, 61]])
print("matriks X:", X_pt)

matriks X: [[12  4  7]
 [25 15 61]]


In [15]:
X_pt.shape
print("ukuran dari matriks X adalah:", X_pt.shape)

ukuran dari matriks X adalah: torch.Size([2, 3])


In [17]:
X_pt[:,0]
print("semua elemen dari kolom pertama matrix X adalah:", X_pt[:,0])

semua elemen dari kolom pertama matrix X adalah: tensor([12, 25])


In [18]:
X_pt[1,:]
print("semua elemen dari baris kedua matrix X adalah:", X_pt[1,:])

semua elemen dari baris kedua matrix X adalah: tensor([25, 15, 61])


In [19]:
#TENSORFLOW
import tensorflow as tf

In [20]:
X_tf = tf.Variable([[12, 4, 7],
              [25, 15, 61]])
print("matriks X:", X_tf)

matriks X: <tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[12,  4,  7],
       [25, 15, 61]], dtype=int32)>


In [22]:
X_tf.shape
print("ukuran dari matrix X adalah:", X_tf.shape)

ukuran dari matrix X adalah: (2, 3)


In [28]:
X_tf[:,0]
print("semua elemen dari kolom pertama matrix X adalah:", X_tf[:,0])

semua elemen dari kolom pertama matrix X adalah: tf.Tensor([12 25], shape=(2,), dtype=int32)


In [29]:
X_tf[1,:]
print("semua elemen dari baris kedua matrix X adalah:", X_tf[1,:])

semua elemen dari baris kedua matrix X adalah: tf.Tensor([25 15 61], shape=(3,), dtype=int32)
