In [ ]:
import numpy as np

In [ ]:
#buat vector x dengan ukuran 3x1
x = np.array([[25], [15],[61]])
x

array([[25],
       [15],
       [61]])

In [ ]:
#hitung panjang vector x
print("panjang vector x adalah:", len(x))

panjang vector x adalah: 3


In [ ]:
#tampilkan ukuran vector x
print("ukuran vector x adalah:", x.shape)

ukuran vector x adalah: (3, 1)


In [ ]:
#tampilkan tipe data dari vector x
print("tipe data dari vector x adalah:", type(x))

tipe data dari vector x adalah: <class 'numpy.ndarray'>


In [ ]:
#akses elemen pertama dari vector x
print("elemen pertama dari vector x adalah:", x[0])


elemen pertama dari matriks x adalah: [25]


In [ ]:
#tampikan tipe data elemen pertama dari vector x
print("tipe data dari elemen pertama vector x adalah:", type(x[0]))

tipe data dari elemen pertama vector x adalah: <class 'numpy.ndarray'>


In [ ]:
#lakukan transpose pada vector x dan simpan pada variabel x_t
x_t = x.T
print("transpose dari vector x adalah:", x.T)

transpose dari matriks x adalah: [[25 15 61]]


In [ ]:
#tampilkan ukuran dari vector x_t
print("ukuran dari vektor x_t adalah:", x_t.shape)

ukuran dari vektor x_t adalah: (1, 3)


In [ ]:
#vector y
y = np.array([[52, 51, 16], [12, 7, 4]])
y

array([[52, 51, 16],
       [12,  7,  4]])

In [ ]:
#transpose vector y
y_t = y.T
print("transpose dari vector y adalah:", y_t)

transpose dari vector y adalah: [[52 12]
 [51  7]
 [16  4]]


In [ ]:
#lakukan soal nomor 2 menggunakan pytorch dan tensorflow
import tensorflow as tf
import torch

In [ ]:
x_tf = tf.Variable([[25],[15],[61]], dtype=tf.int16)
x_tf

<tf.Variable 'Variable:0' shape=(3, 1) dtype=int16, numpy=
array([[25],
       [15],
       [61]], dtype=int16)>

In [ ]:
x_pt = torch.tensor([[25],[15],[61]], dtype=torch.int16)
x_pt

tensor([[25],
        [15],
        [61]], dtype=torch.int16)

In [ ]:
#menampilkan ukuran vector x dengan tensorflow
x_tf.shape
print("ukuran vector x adalah:", x_tf.shape)

ukuran vector x adalah: (3, 1)


In [ ]:
#menampilkan vector x dengan pytorch
x_pt.shape
print("ukuran vector x adalah:", x_pt.shape)

ukuran vector x adalah: torch.Size([3, 1])


In [ ]:
#menampilkan elemen pertama dari vector x dengan pytoch
x_pt[0]
print("elemen pertama dari vector x adalah:", x_pt[0])

elemen pertama dari vector x adalah: tensor([25], dtype=torch.int16)


In [ ]:
#menampilkan elemen pertama dari vector x dengan tensorflow
x_tf[0]
print("elemen pertama dari vector x adalah:", x_tf[0])

elemen pertama dari vector x adalah: tf.Tensor([25], shape=(1,), dtype=int16)


In [ ]:
#mencari vector transpose x dengan pytorch
x_pt.T
print("transpose dari vector x adalah", x_pt.T)

In [ ]:
#mencari vector transpose x dengan tensorflow
x_tf_transpose = tf.transpose(x_tf)
print("transpose dari vector x adalah", x_tf_transpose)

transpose dari matriks x adalah tf.Tensor([[25 15 61]], shape=(1, 3), dtype=int16)
